##listener Configurations##
http:
  listner:
    host: "localhost"
    port: "8081"
    
  requestor:
    url: "https://sandbox.boostr.com/api/accounts"
    Accept: "application/vnd.boostr.public"
    Content-Type: "application/json"
    
  JWTtoken:  
    tokenurl: "https://sandbox.boostr.com/api/user_token"
