{
  "headers": {
    "host": "localhost:8081",
    "connection": "keep-alive",
    "content-length": "427",
    "sec-ch-ua-platform": "\"Windows\"",
    "authorization": "eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MzIxNjg4MjcsInN1YiI6MTA5ODgsImNvbXBhbnlfaWQiOjIzMywicmVmcmVzaCI6IjYyYzc2ZjRlYzkwMjJjMTdlZmJjOTdkNWFhNjUwOTVjY2EyN2RkOWMifQ.Is5YdKkPL3eJI8_ItEmhPY4pi9iRjLeJGscyhyC9mLc",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0",
    "accept": "application/vnd.boostr.public",
    "sec-ch-ua": "\"Chromium\";v=\"130\", \"Microsoft Edge\";v=\"130\", \"Not?A_Brand\";v=\"99\"",
    "content-type": "application/json",
    "sec-ch-ua-mobile": "?0",
    "origin": "http://localhost:8081",
    "sec-fetch-site": "same-origin",
    "sec-fetch-mode": "cors",
    "sec-fetch-dest": "empty",
    "referer": "http://localhost:8081/console/",
    "accept-encoding": "gzip, deflate, br, zstd",
    "accept-language": "en-US,en;q=0.9,en-IN;q=0.8"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/createAccounts",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/createAccounts",
  "listenerPath": "/api/*",
  "relativePath": "/api/createAccounts",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/createAccounts",
  "rawRequestPath": "/api/createAccounts",
  "remoteAddress": "/127.0.0.1:62352",
  "requestPath": "/api/createAccounts"
}